name: Build and Run Command

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Instalar dependencias
      run: yarn install

    - name: Construir y Ejecutar
      run: yarn build && node dist/index.js
